### ISSUE TITLE
Update Bootstrap to use existing Configurator

### ISSUE THREAD

**Issue by foxycode** [mrtnzlml/testbench#16]
If I want to inherit tests from my own class and I want that class to be autoloaded, I need to create `Nette\Configurator` and `RobotLoader` right away in `bootstrap.php`. I don't need to create container, so I think needed `Testbench` extension stil could be added later when `Container` is created.

**Comment by mrtnzlml** [comment]
Can you please elaborate this issue more with examples? I am not sure what is your problem. Thanks... :)

**Comment by foxycode** [comment]
Simply:

``` php
<?php

namespace Test\AdminModule\Presenters;

use Nette;
use Tester\Assert;


require __DIR__ . '/../../bootstrap.php';


class ActuarialPresenterTest extends \Test\PresenterTestBase
{
    // ...
```

Class `Test\PresenterTestBase` is my own class located in `tests/libs`, which can't be found because `RobotLoader` isn't created in `bootstrap.php`.

**Comment by mrtnzlml** [comment]
Oh, I see. It is interesting I never noticed this problem, because I use different approach. You can use Composer autoloading (the best solution) or independent RobotLoader (see [documentation](https://github.com/nette/robot-loader/blob/master/readme.md#robotloader-comfortable-autoloading)). I cannot think about simple solution. It's not possible to create DIC in `bootstrap.php`, because of performance issues...

Or what did you mean with this?

> so I think needed Testbench extension stil could be added later when Container is created

**Comment by foxycode** [comment]
@mrtnzlml 

1) I don't need to create DIC in bootstrap, just `RobotLoader`, or reather `Configurator`. Testbench can take that instance and create container later after registering own extensions. It would be IMO much simplier that creating configurator in callback.

2) Which performane issues do you have in mind?

**Comment by mrtnzlml** [comment]
I am still not sure if I understand you. Bootstrap should be as simple as possible. This is why it's used callback, because in Nette\Tester bootstrap is called every time, but callback is called only if it's needed (not every time). It's much more better than creating whatever you want in bootstrap...

If I am wrong, can you please create very simple example? I am sorry for my stupidity... :)

**Comment by foxycode** [comment]
@mrtnzlml Ok, I am starting to understand where your point is. You are speaking about tests which doesn't need `Container` or even `Configurator` to run. I don't have such tests so I couldn't imagine your point.

What I am trying to achive is having `RobotLoader` registered in bootstrap so tests can inherit from autoloaded class. Your example code in this repo made this to me difficult before I understood how you thinking about it. What about update example so robot loader is created outside callback?

**Comment by mrtnzlml** [comment]
You can try something like this outside of callback:

``` php
(new \Nette\Loaders\RobotLoader)
    ->addDirectory([
        __DIR__,
    ])->register();
```

It is ordinary bootstrap - you can do whatever you want or you are familiar with, only one exception is container handling. But I can create another example, it's a good idea. Does it solve your problem?

**Comment by foxycode** [comment]
I'm not happy with it, but it's working, so closing.
