### ISSUE TITLE
Contributte

### ISSUE THREAD

**Issue by f3l1x** [mrtnzlml/testbench#49]
Hi!

According to this tweet: https://twitter.com/mrtnzlml/status/886504837856337921

I would like to move this package under contributte namespace and try to maintain it. Do you agree? :-)

I use similar approach and have many ideas how to merge it or develop it.

**Comment by mrtnzlml** [comment]
Sí. This package really needs further improvements because it's not written well and tests are a little bit [flaky](https://github.com/mrtnzlml/testbench/issues/46). For the next major version, I would recommend to remove scaffolding (it was just a good marketing trick) and refactor it completely. Especially the `TPresenter` part and database mock system.

What should I do now?

**Comment by f3l1x** [comment]
Glad you say that. I really like refactoring 🐕 

Please arrange the transfer under **contributte** organization. Thank you.
