### ISSUE TITLE
DB platform adapters

### ISSUE THREAD

**Issue by jiripudil** [mrtnzlml/testbench#7]
Since you've made this into a library, I think it would be nice to delegate `createDatabase` and `dropDatabase` methods responsibilities onto adapters for different database platforms. The code was originally written for PostgreSQL and can be needlessly complicated for other platforms (e.g. in MySQL you can completely avoid the double reconnecting). What do you think?

**Comment by mrtnzlml** [comment]
It's definitely my plan. I would like to add at least NDB. That's why I wrote [Doctrine only - stay tuned here](https://github.com/mrtnzlml/testbench#minimal-code). I saw that NDB is already implemented in another repo (don't remember which one) so it shouldn't be hard. Well with traits maybe, but... Stay tuned... :)

**Comment by jiripudil** [comment]
Well, I thought more of a slightly different behavior depending on the underlying database platform, not the database layer, but still, :+1:

**Comment by mrtnzlml** [comment]
Thanks for reporting. `TDoctrine` is now able to change database using `USE` statement for `MySqlPlatform`. Now I have to think more about another database layers... :)
